"""is_admin added

Revision ID: 5ca8708408c2
Revises: 6a4fecb9a66e
Create Date: 2022-07-12 15:59:03.760784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ca8708408c2'
down_revision = '6a4fecb9a66e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
