"""updated

Revision ID: 6a4fecb9a66e
Revises: 7070913f39dd
Create Date: 2022-07-12 15:55:21.337273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4fecb9a66e'
down_revision = '7070913f39dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
