"""updated

Revision ID: 7070913f39dd
Revises: 2e7d59430723
Create Date: 2022-07-12 15:53:12.950571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7070913f39dd'
down_revision = '2e7d59430723'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
